version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/aws-nodejs
hooks:
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ubuntu
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: ubuntu
